#!/usr/bin/env bash
# Configure Ubuntu server with specific DNS resolutions

if [[ "$EUID" -ne 0 ]]; then
  echo "Please run this script as root"
  exit 1
fi
cp /etc/hosts /etc/hosts.bak
sed -i 's/127.0.0.1/127.0.0.2/' /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
