#!/usr/bin/env bash
# Configure Ubuntu server to set custom DNS resolutions for localhost and facebook.com

[ "$EUID" -ne 0 ] && echo "Please run as root" && exit 1
cp /etc/hosts /etc/hosts.bak
sed 's/^127.0.0.1/127.0.0.2/' /etc/hosts > /tmp/hosts.new && echo "8.8.8.8 facebook.com" >> /tmp/hosts.new
mv /tmp/hosts.new /etc/hosts
echo "Changes applied. Backup is /etc/hosts.bak"
